### ISSUE TITLE
Is this plugin still supported?

### ISSUE THREAD

**Issue by rpovelones** [dachcom-digital/acf-yoast-seo-validation#16]
Hi,

Thank you for your great work on this plugin/script. It is really great how minimal it is. However, I am wondering if it is still being supported? It looks like there haven't been any commits in a long time. I would really like to use this, but it does not appear to be working w/ WP 4.9.7, Yoast 8.1.2, and ACF 5.7.1. 

Thanks.
Robert

**Comment by TimVevida** [comment]
Hi Robert,

The plugin is still supported. It was working until ACF 5.7.0, which introduced a breaking change. I am working on a fix.

**Comment by TimVevida** [comment]
The plugin has been updated to support the latest versions of Yoast SEO and ACF.

**Comment by rpovelones** [comment]
Thanks so much @TimVevida ! Yes it looks to be working again! Thank you so much for your work on this plugin!!
