### ISSUE TITLE
acf is not defined

### ISSUE THREAD

**Issue by rafal-sokolowski** [dachcom-digital/acf-yoast-seo-validation#18]
PHP 7.0.32 (cli) (built: Oct 23 2018 11:55:23) ( NTS )
WordPress 4.9.8
Advanced Custom Fields Pro 5.8.0-beta2
Yoast SEO 9.2
Dachcom ACF - YOAST SEO Validation 5.3.2.2

 **ReferenceError: acf is not defined in acf_yoast.js:168:7**

<pre>$(document).ready(function() {
  acf.add_action('load_field', acfPlugin.setContent.bind(acfPlugin));</pre>

**Comment by TimVevida** [comment]
Any problems with the non-beta version 5.7.7 of ACF Pro?

**Comment by rafal-sokolowski** [comment]
<img width="887" alt="acf-is-not-defined" src="https://user-images.githubusercontent.com/10531472/49018874-d2412400-f18c-11e8-8041-6197b8401726.png">

**Comment by yratof** [comment]
Any news on if this is fixed?

**Comment by TimVevida** [comment]
Sorry, I somehow missed the latest messages.

It seems the script is loaded on every page (the screenshot shows the plugin overview page). This is not necessary. It should only be loaded on pages that edit a post/page.

On pages that do edit a post/page, no error message is shown and the script works correctly.
