### ISSUE TITLE
Conflict when Using "Wordpress Page Widgets" by CodeAndMore

### ISSUE THREAD

**Issue by rjgnyc** [dachcom-digital/acf-yoast-seo-validation#6]
When I have your plugin activated, the Wordpress Page Widgets plugin won't let me drag/drop or expand fields managed within that widget (dragging and dropping still works overall). The error I get when looking in Chrome is below:

Uncaught TypeError: acf.add_action is not a function
http://[website]/wp-admin/admin-ajax.php Failed to load resource: net::ERR_CONNECTION_TIMED_OUT

Turning off your plugin makes things work just fine once again.

I'm not sure which plugin is causing the conflict, but I'd definitely like some guidance on what to do to fix it, because I definitely want to have my custom fields assessed by Yoast, and I love what your plugin does overall.

–Richard

**Comment by TimVevida** [comment]
Hello Richard,
The plugin only works for ACF PRO, version 5.0 and up. What is your version of ACF?
Regards, Tim

**Comment by rjgnyc** [comment]
Hi Tim!

That was the issue, I'm on normal ACF (v4.4.5), not PRO.

–Richard
