### ISSUE TITLE
JS Error preventing removal of flexible content block

### ISSUE THREAD

**Issue by marcc1213** [dachcom-digital/acf-yoast-seo-validation#8]
Hi - first, I love the script, it has come in very handy (not a fan of Yoast, but clients love it so what can ya do?). Anyhow, on attempting to remove a flexible content block I get the following error:

*_Uncaught TypeError: Cannot convert undefined or null to object
*_
Will take a look ASAP on my end, but was hoping you might have some insight.

Thanks!

**Comment by solverat** [comment]
i just pushed TimVevida's PR into master, may you check it again so we can close this issue.

**Comment by TimVevida** [comment]
No response, closing.

**Comment by yjeanrenaud** [comment]
this is happening to me too. I had to deactive the plugin to fix that

**Comment by mjot** [comment]
@yjeanrenaud Try this plugin from Yoast: [ACF Content Analysis forYoast](https://de.wordpress.org/plugins/acf-content-analysis-for-yoast-seo/)
